# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore
        dotnet publish -c Release -o ../dotnet_publish -r linux-x64 --self-contained true /p:UseAppHost=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Dotnet Publish
      uses: EasyDesk/action-dotnet-publish@v1.0.0
      with:
        # Path to the project to publish.
        path: .
        output-dir: out
        build-configuration: Release
        skip-build: false
          
